### ISSUE TITLE
From as Original Sender

### ISSUE THREAD

**Issue by nodrog** [thoughtbot/griddler-cloudmailin#6]
Hello

I am trying to get my email processor to have the correct original sender, currently i am just getting the email from cloudmailin in the from.

The email i want is the original sender address, and it is correct in the headers.

Is there any reason why the headers are not sent through. or if i where to add them that i should not rely on this as the original sender?

Many thanks

**Comment by dominicsayers** [comment]
This was fixed in [v1.0.2](https://github.com/thoughtbot/griddler-cloudmailin/pull/4)

The latest version on RubyGems is v0.0.1 - sorry but I don't have the ability to release a new version. Please ask @calebthompson if you would like him to release it.

To use the current version put this in your Gemfile: `gem 'griddler-cloudmailin', github: 'thoughtbot/griddler-cloudmailin'`
